/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CristoBook;

import javax.swing.JOptionPane;

/**
 *
 * @author Fernández
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        Vista v = new Vista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        PanelIzq = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PanelDrch = new javax.swing.JPanel();
        IniciarSesion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        Pass = new javax.swing.JLabel();
        bttIniciarSesion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPassword = new javax.swing.JPasswordField();
        IconLock = new javax.swing.JLabel();
        IconPass = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        Exit = new javax.swing.JLabel();
        jLabelregistroAqui = new javax.swing.JLabel();
        jLabelRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzq.setBackground(new java.awt.Color(64, 170, 173));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Modeka", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CristoBook");

        javax.swing.GroupLayout PanelIzqLayout = new javax.swing.GroupLayout(PanelIzq);
        PanelIzq.setLayout(PanelIzqLayout);
        PanelIzqLayout.setHorizontalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addGroup(PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(PanelIzqLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(logo)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelIzqLayout.setVerticalGroup(
            PanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIzqLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(logo)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        getContentPane().add(PanelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 600));

        PanelDrch.setBackground(new java.awt.Color(47, 31, 99));

        IniciarSesion.setFont(new java.awt.Font("Gotham", 0, 36)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesion.setText("Iniciar Sesión");

        jLabel2.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");

        txtLogin.setBackground(new java.awt.Color(47, 31, 99));
        txtLogin.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(64, 170, 173));
        txtLogin.setBorder(null);
        txtLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        Pass.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText("PASSWORD");

        bttIniciarSesion.setBackground(new java.awt.Color(47, 31, 99));
        bttIniciarSesion.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        bttIniciarSesion.setForeground(new java.awt.Color(204, 204, 204));
        bttIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/bttnIniciarSesion.png"))); // NOI18N
        bttIniciarSesion.setBorder(null);
        bttIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttIniciarSesionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttIniciarSesionMousePressed(evt);
            }
        });
        bttIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIniciarSesionActionPerformed(evt);
            }
        });

        jPassword.setBackground(new java.awt.Color(47, 31, 99));
        jPassword.setForeground(new java.awt.Color(64, 170, 173));
        jPassword.setBorder(null);

        IconLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/icons8_user_30px.png"))); // NOI18N

        IconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/icons8_user_30px.png"))); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(47, 31, 99));
        jCheckBox1.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("Recuérdame");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/icons8_delete_24px.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        jLabelregistroAqui.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabelregistroAqui.setForeground(new java.awt.Color(255, 255, 255));
        jLabelregistroAqui.setText("aquí");
        jLabelregistroAqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelregistroAqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelregistroAquiMouseClicked(evt);
            }
        });

        jLabelRegistro.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setText("¿No tienes cuenta? Registrate");

        javax.swing.GroupLayout PanelDrchLayout = new javax.swing.GroupLayout(PanelDrch);
        PanelDrch.setLayout(PanelDrchLayout);
        PanelDrchLayout.setHorizontalGroup(
            PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelDrchLayout.createSequentialGroup()
                .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDrchLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Exit))
                    .addGroup(PanelDrchLayout.createSequentialGroup()
                        .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDrchLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Pass)
                                        .addComponent(jLabel2)
                                        .addComponent(jCheckBox1)
                                        .addGroup(PanelDrchLayout.createSequentialGroup()
                                            .addComponent(IconPass)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelDrchLayout.createSequentialGroup()
                                            .addComponent(IconLock)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(IniciarSesion)))
                            .addGroup(PanelDrchLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(bttIniciarSesion)))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDrchLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabelRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelregistroAqui)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDrchLayout.setVerticalGroup(
            PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDrchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit)
                .addGap(72, 72, 72)
                .addComponent(IniciarSesion)
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconLock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Pass)
                .addGap(18, 18, 18)
                .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(14, 14, 14)
                .addComponent(bttIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelregistroAqui))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDrch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 410, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void bttIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIniciarSesionActionPerformed
        
    }//GEN-LAST:event_bttIniciarSesionActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void bttIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttIniciarSesionMouseClicked
        String Usuario = "Admin";
        String Contraseña = "0123456789";
        
        String Password =  new String(jPassword.getPassword());
        
        if(txtLogin.getText().equalsIgnoreCase(Usuario) &&  Password.equals(Contraseña)){
            
            VistaAdmin admin =  new VistaAdmin();
            admin.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Usuario / Contraseña incorrectos");
        }
    }//GEN-LAST:event_bttIniciarSesionMouseClicked

    private void bttIniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttIniciarSesionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttIniciarSesionMousePressed

    private void jLabelregistroAquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistroAquiMouseClicked
        CrearUsuario usu = new CrearUsuario();
        usu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelregistroAquiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel IconLock;
    private javax.swing.JLabel IconPass;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JPanel PanelDrch;
    private javax.swing.JPanel PanelIzq;
    private javax.swing.JLabel Pass;
    private javax.swing.JButton bttIniciarSesion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelregistroAqui;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
